<hr><hr>

# Programação com arrays: introdução ao NumPy

In [1]:
#conda install numpy
import numpy as np

# Construindo Array

In [2]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [3]:
np.array([4,5,6,9])

array([4, 5, 6, 9])

In [4]:
npa = np.array(range(10))
npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
npa_zeros = np.zeros(10)
npa_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
npa_ones = np.ones(10)
npa_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
npa_zeros = np.zeros(10, dtype=int)
npa_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
npa_completo = np.full(10,42)
npa_completo

array([42, 42, 42, 42, 42, 42, 42, 42, 42, 42])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Aleatorios

In [112]:
#aleatorios
npa = np.random.randint(10, size = (3,4))
npa

array([[3, 9, 6, 6],
       [1, 6, 6, 8],
       [3, 4, 0, 0]])

In [121]:
np.random.seed(42)
npa = np.random.randint(10, size = (3,4))
npa

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [16]:
np.array([[4,7,0,6],
          [0,5,5,9],
          [4,6,2,4]])

array([[4, 7, 0, 6],
       [0, 5, 5, 9],
       [4, 6, 2, 4]])

# Propriedades

In [18]:
npa_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
npa_zeros.ndim

1

In [19]:
npa.ndim

2

In [20]:
npa_zeros.shape

(10,)

In [21]:
npa.shape

(3, 4)

In [22]:
npa_zeros.size

10

In [23]:
npa.size #3x4

12

In [24]:
npa_zeros.dtype

dtype('int32')

In [25]:
npa_ones.dtype

dtype('float64')

In [26]:
npa_ones.nbytes

80

In [27]:
npa_zeros.nbytes

40

# Indexando e Acesso

In [28]:
npa = np.arange(10)*10
npa

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
npa[0]

0

In [30]:
npa[3]

30

In [31]:
npa[-1]

90

In [32]:
npa[-3]

70

In [33]:
mat = np.array([[4,7,0,6],[0,5,5,9],[4,6,2,4]])
mat

array([[4, 7, 0, 6],
       [0, 5, 5, 9],
       [4, 6, 2, 4]])

In [34]:
mat[1,3]

9

### Subarray

In [35]:
npa = np.arange(10)*10
npa

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
npa[:4]

array([ 0, 10, 20, 30])

In [37]:
npa[4:]

array([40, 50, 60, 70, 80, 90])

In [38]:
npa[4:7]

array([40, 50, 60])

In [39]:
npa[::2]

array([ 0, 20, 40, 60, 80])

In [40]:
npa[2:7:2]

array([20, 40, 60])

# Exercicio

1. criar um numpy array de tamanho 20 aleatório (a sua escolha). <br>
2. remover os 5 primeiros e os 5 últimos elementos do array.

In [43]:
np.random.rand(20)

array([40.33742905, 42.69098253, 39.22065203, 49.88677454, 43.28997081,
       48.75959646, 39.10235594, 39.51091252, 44.6434458 , 44.79474479,
       43.00552214, 32.82013018, 44.83258183, 43.49197592, 37.42399688,
       47.51345697, 39.10566585, 44.76862398, 33.32154684, 36.44002892])

In [44]:
npa = np.random.randint(1000, size = 20)
npa

array([543, 798, 719,  46, 979, 128,  24, 416, 271, 444, 351, 169, 692,
       703, 791, 501,  63, 198, 847, 728])

In [45]:
npa[5:]

array([128,  24, 416, 271, 444, 351, 169, 692, 703, 791, 501,  63, 198,
       847, 728])

In [46]:
npa[:-5]

array([543, 798, 719,  46, 979, 128,  24, 416, 271, 444, 351, 169, 692,
       703, 791])

In [47]:
npa[5:-5]

array([128,  24, 416, 271, 444, 351, 169, 692, 703, 791])

In [48]:
npa.sort()

In [49]:
npa

array([ 24,  46,  63, 128, 169, 198, 271, 351, 416, 444, 501, 543, 692,
       703, 719, 728, 791, 798, 847, 979])

In [50]:
npa[5:-5]

array([198, 271, 351, 416, 444, 501, 543, 692, 703, 719])

# Reshape

In [51]:
vet = np.arange(1,65)
vet

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [52]:
xadrez = vet.reshape(8,8)
xadrez

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [53]:
vet1 = np.arange(10)
vet2 = np.random.randint(10,size=5)
print(vet1)
print(vet2)

[0 1 2 3 4 5 6 7 8 9]
[6 8 5 2 8]


In [54]:
np.concatenate([vet1,vet2])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 8, 5, 2, 8])

In [55]:
mat1 = np.array([[2],[6]])
mat1

array([[2],
       [6]])

In [56]:
mat2 = np.array([[12],[5]])
mat2

array([[12],
       [ 5]])

In [57]:
np.vstack([mat1,mat2])

array([[ 2],
       [ 6],
       [12],
       [ 5]])

In [58]:
np.hstack([mat1,mat2])

array([[ 2, 12],
       [ 6,  5]])

# Splitting

In [59]:
npa = np.random.rand(10)
npa

array([0.89918341, 0.49166386, 0.4687979 , 0.09259887, 0.52589808,
       0.22734207, 0.92075623, 0.72786988, 0.29590768, 0.91283192])

In [60]:
np.split(npa,[2])

[array([0.89918341, 0.49166386]),
 array([0.4687979 , 0.09259887, 0.52589808, 0.22734207, 0.92075623,
        0.72786988, 0.29590768, 0.91283192])]

In [61]:
np.split(npa,[2,7])

[array([0.89918341, 0.49166386]),
 array([0.4687979 , 0.09259887, 0.52589808, 0.22734207, 0.92075623]),
 array([0.72786988, 0.29590768, 0.91283192])]

In [62]:
res = np.split(npa,[2,7])
res[2]

array([0.72786988, 0.29590768, 0.91283192])

In [63]:
res1,res2,res3 = np.split(npa,[2,7])

In [64]:
print(res1)

[0.89918341 0.49166386]


In [65]:
print(res2)

[0.4687979  0.09259887 0.52589808 0.22734207 0.92075623]


In [66]:
print(res3)

[0.72786988 0.29590768 0.91283192]


In [67]:
xadrez

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [68]:
np.hsplit(xadrez,[4])

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [69]:
np.vsplit(xadrez,[4])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

# Agregações e Operadores

In [70]:
vet = np.random.randint(10, size = 10)
vet

array([1, 0, 1, 4, 1, 8, 4, 0, 8, 5])

In [79]:
vet

array([0, 0, 1, 1, 1, 4, 4, 5, 8, 8])

In [71]:
#media
soma = 0
for i in vet:
    soma += i
soma/10

3.2

In [72]:
#media
vet.mean()

3.2

In [73]:
vet.sum()

32

In [74]:
np.arange(1,101).sum()

5050

In [75]:
vet.max()

8

In [76]:
vet.min()

0

In [77]:
np.median(vet)

2.5

In [80]:
np.std(vet)

2.9257477676655586

In [81]:
np.var(vet)

8.559999999999999

In [82]:
np.std(vet)**2

8.559999999999999

# Operações 

In [83]:
vet = np.ones(10)
vet

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [84]:
vet2 = vet*8
vet2

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [85]:
vet2 = vet+8
vet2

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [100]:
vet3 = np.arange(10)
vet3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
vet2+vet3

array([ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.])

In [88]:
np.matmul(vet2,vet3)

405.0

In [89]:
vet = [5,8,2,3,4]
vet

[5, 8, 2, 3, 4]

In [96]:
vet.sort(reverse=1)

In [97]:
vet

[8, 5, 4, 3, 2]

In [102]:
avet = np.array([5,8,2,3,4])
avet

array([5, 8, 2, 3, 4])

In [104]:
avet.sort()
avet

array([2, 3, 4, 5, 8])

In [105]:
avet[::-1]

array([8, 5, 4, 3, 2])

In [106]:
avet = np.array(['c','a','b'])
avet.sort()
avet

array(['a', 'b', 'c'], dtype='<U1')